language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7
matrix:
  include:
    - jdk: "oraclejdk8"
      env: AUTHOR_TESTING=1 RELEASE_TESTING=1
    - jdk: "oraclejdk8"
      env: COVERAGE=1
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - local-lib cache
  - perl -V
  - build-dist
  - cp MANIFEST.SKIP $BUILD_DIR # so xt/manifest.t can work right
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
before_script:
  - coverage-setup
script:
  - make
  - prove -b t/01_init.t # set up config as parallel races and breaks
  - prove -b -j$(test-jobs) $(test-files)   # parallel testing
after_success:
  - coverage-report
notifications:
  irc:
    channels:
    - "irc.perl.org#graphql-perl"
    on_failure: always
    skip_join: true
